---
output: html_document
---
 
```{r knit_opts, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r setup, include = FALSE}
# devtools::install_github("Rdatatable/data.table")
# devtools::install_github("adamdsmith/geobird")
# devtools::install_github("bhaskarvk/leaflet@develop")
# devtools::install_github("bhaskarvk/leaflet.extras")
pacman::p_load(raster, dplyr, readxl, sp, rgdal, rgeos, geobird, readr,
               leaflet, leaflet.extras, tidyr, viridis, geojsonio)

# Load and filter RAPP database
keep_rapp <- c(1.08, 1.20, seq(1.30, 1.43, 0.01), 1.71, 5.41, 5.04, 5.07, 5.47, 6.09, 7.06)
keep_rapp <- formatC(round(keep_rapp, 2), format='f', digits=2)
rapp <- read_excel("./Data/Allregionmeasures.xls", skip = 1) %>%
  dplyr::select(Zone, Complex, Location, RappMeasure, FY, Target, Actual) %>%
  filter(grepl(paste(keep_rapp, collapse = "|"), RappMeasure))

# A few edits to make compatible
rapp$Location <- gsub("Dale Bumpers ", "", rapp$Location)
rapp$Location <- gsub("DArbonne", "D'arbonne", rapp$Location)
rapp$Location <- gsub("J.N. Ding", "J. N. Ding", rapp$Location)
rapp$Location <- gsub("ACE Basin", "Ace Basin", rapp$Location)
```

```{r load_shp}
# Load US counties and refuge polygons
ref <- readOGR("./GIS", "refuges", verbose = FALSE)
ref@data <- mutate(ref@data,
                   ORGNAME = geobird:::Cap(ORGNAME),
                   Location = gsub("National Wildlife Refuge", "NWR", ORGNAME)) %>%
  select(Location)
```

```{r compatability_check}
# Confirm compatability
refs_rapp <- sort(unique(rapp$Location))
refs_poly <- sort(unique(ref$Location))
# if (length(refs_rapp[which(!(refs_rapp %in% refs_poly))]) > 0) {
#   cat("KEEP TRYING!\nThis one still doesn't match!\n")
#   refs_rapp[which(!(refs_rapp %in% refs_poly))]
# } else cat("NICE JOB!")

# Filter shapefile
ref <- ref[ref$Location %in% refs_rapp, ]
```

```{r tidy_rapp}
rapp <- rapp %>% 
  mutate(Zone = as.integer(gsub("R4 Zone ", "", Zone)),
         Complex = gsub(" Total| Complex", "", Complex),
         RAPP = substr(RappMeasure, 1, 4),
         RAPP_cat = gsub("\\d.\\d\\d[[:space:]]+", "", RappMeasure),
         Actual = as.numeric(gsub(",", "", Actual))) %>%
  select(Zone, Complex, Location, RAPP, RAPP_cat, Actual) %>%
  as.data.frame()

# Look up table for RAPP codes with tidied text
rapp_lu <- unique(rapp[, c("RAPP", "RAPP_cat")]) %>%
  mutate(RAPP_cat = gsub("of ", "", RAPP_cat),
         RAPP_cat = gsub(" for | by ", ": ", RAPP_cat),
         RAPP_cat = gsub(" or ", "/", RAPP_cat),
         RAPP_cat = gsub("Number", "#", RAPP_cat),
         RAPP_cat = gsub("identified ", "", RAPP_cat),
         RAPP_cat = gsub("non-native, ", "", RAPP_cat))

rapp_wide <- rapp %>%
  select(Zone, Complex, Location, RAPP, Actual) %>%
  spread(RAPP, Actual) %>%
  mutate(lat = coordinates(ref)[, 2],
         lon = coordinates(ref)[, 1])

save(rapp_wide, rapp_lu,
       file = "./Output/RAPP_tables.rda")
```

```{r geojson_creation}
# Join RAPP table to shapefile, then tidy
ref@data <- left_join(ref@data, rapp_wide, by = "Location") 
# geojson_write(ref, file = "./GIS/refuge_rapp.geojson")
```

```{r map, fig.height=7, fig.width=10}
#gj <- read_file("./GIS/refuge_rapp.geojson")
sp_gj <- function(sp_obj){
  tf <- tempfile(fileext = ".geojson")
  suppressMessages(geojson_write(sp_obj, file = tf))
  gs <- read_file(tf)
  invisible(file.remove(tf))
  return(gs)
}

# Create map
p <- leaflet() %>%
  setView(-81.375962, 32.248141, 5) %>%
  # Base map 
  addProviderTiles("CartoDB.DarkMatter") %>%
  addBootstrapDependency()

# Find RAPP categories reported by at least 10 refuges
rapp_lu <- rapp_lu[which(colSums(rapp_wide[, rapp_lu$RAPP] != 0) >= 10), ]

for (r in rapp_lu$RAPP) {
  
  d <- ref[ref[[r]] > 0, c("Location", "Zone", "Complex", r)]
  gj <- sp_gj(d)
  
  # if (length(d) > 0) {
    values <- rapp_wide[[r]][rapp_wide[[r]] > 0]
  # } else {
  #   values <- 0
  # }
  # n_breaks <- max(n_distinct(fivenum(values)) - 1, 2)

  # Set up separate overlays/colors by rapp measure
  rapp_colors = colorQuantile(palette = viridis(4), domain = values)
  grp <- rapp_lu[rapp_lu$RAPP == r, "RAPP_cat"]
  
  # if (length(d) > 0) {
    p <- p %>% 
      addGeoJSONChoropleth(
        gj,
        valueProperty = r,
        opacity = 1, fillOpacity = 1,
        scale = viridis(4), 
        mode = "q", steps = 4,
        labelProperty = c("Location"),
        popupProperty = propstoHTMLTable(
          props = c("Zone", "Complex", "Location"),
          table.attrs = list(class='table table-striped table-bordered'), drop.na = T),
        color = rapp_colors(values), weight = 10,
        legendOptions = legendOptions(title = grp),
        highlightOptions = highlightOptions(
          weight=2, color = rapp_colors(values)),
        group = grp)
  # } else {
  #   p <- p %>% 
  #     addGeoJSONChoropleth(
  #       gj, 
  #       valueProperty = r,
  #       legendOptions = legendOptions(title = grp))
  # }
}

p <- p %>% addLayersControl(baseGroups = rapp_lu$RAPP_cat,
                       options = layersControlOptions(collapsed = FALSE)) %>%
  addFullscreenControl()
p

```







